# Indentation and width settings
max_width = 120   # Maximum width of a line in characters
hard_tabs = false # Use spaces rather than tabs
tab_spaces = 4    # Number of spaces per tab

# Formatting style
use_small_heuristics = "Max"    # Maximize line width before splitting
normalize_doc_attributes = true # Normalize doc attributes (e.g., collapse `///`)

# Import and group settings
imports_granularity="Module"          # Merge all imports into a single use statement as long as they have the same visibility.
imports_layout = "Horizontal"      # Item layout inside a imports block
group_imports = "StdExternalCrate" # Group imports by type
reorder_imports = true             # Reorder imports alphabetically within groups

# Function and method formatting
fn_single_line = true           # Allow single-line function signatures
fn_params_layout = "Compressed" # Compact formatting of function parameters

# Struct and enum settings
struct_field_align_threshold = 80 # Align fields in structs if within the threshold
enum_discrim_align_threshold = 80 # Align discriminants in enums if within threshold

# Control flow settings
control_brace_style = "AlwaysSameLine" # Place opening braces of blocks on a new line
match_arm_blocks = true                # Wrap match arms in blocks if multiline
single_line_if_else_max_width = 120

# Miscellaneous settings
combine_control_expr = true # Combine simple expressions in control flows
blank_lines_upper_bound = 1 # Limit the number of blank lines in a row
newline_style = "Unix"      # Use Unix-style newlines (\n)

# Comment settings
format_code_in_doc_comments = true # Format code snippets inside doc comments
comment_width = 120
wrap_comments = true

# Edition settings
edition = "2024" # Specify the Rust edition
